---
- name: zabbix playbook
  hosts: prod
  vars:
    - proxy_ip: 192.168.110.2 
    - cst_name: TEST
  tasks:
    - name: update repo
      shell: rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm
      ignore_errors: true
    - name: clean all task
      shell: dnf clean all
    - name: install zabbix agents pkgs
      yum:
        name: 
          - zabbix-agent2 
          - zabbix-agent2-plugin-*
        state: present 
    - name: start and enable zabbix service
      service:
        name: zabbix-agent2
        state: restarted
        enabled: yes  
    - name: Modify Zabbix configration file add Server IP paramter
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^Server="
        line: "Server={{ proxy_ip }}"
        state: present
    - name: Modify Zabbix configration file server add ServerActive paramter
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^ServerActive="
        line: "ServerActive={{ proxy_ip }}"
        state: present
    - name: Modify Zabbix configration file server add Hostname paramter
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^Hostname="
        line: "Hostname= {{ cst_name }}-{{ ansible_facts['hostname'] }}"
    - name: Modify Zabbix Configure file add HostMetadataItem paramter
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^# HostMetadataItem='
        insertafter: '^# HostMetadataItem= ' 
        line: 'HostMetadataItem=system.uname'
    - name: Add AllowKey paramter to config file 
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        line: 'AllowKey=system.run[*]'
        insertafter: '#       Unless another system.run[*] rule is specified DenyKey=system.run[*] is added by default.'       
    - name: restart zabbix agent service 
      service:
        name: zabbix-agent2.service
        state: restarted









